name: .NET Core

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Build with dotnet
      run: dotnet build --configuration Release
    - name: Test with dotnet
      run: dotnet test --configuration Release
    - name: Restore dotnet tools
      run: dotnet tool restore
    - name: Test with stryker
      working-directory: UnitTests
      run: dotnet stryker -f stryker-config.json -r dashboard --dashboard-api-key ${{ secrets.STRYKER_DASHBOARD_API_KEY }}
